import { createHash } from "node:crypto";
import { uuidv7 } from "@earendil-works/pi-ai";
import type { AgentMessage, ExtensionAPI } from "@earendil-works/pi-coding-agent";

const SUMMARY_PROVIDER = "antigravity";
const SUMMARY_MODEL_ID = "gemini-3.6-flash-high";

const summaryCache = new Map<string, string>();
const inFlightSummaries = new Map<string, Promise<string>>();

function hashImage(data: string): string {
  return createHash("sha256").update(data).digest("hex");
}

async function summarizeImage(
  data: string,
  mimeType: string,
  targetModelId: string,
  ctx: any,
): Promise<string> {
  const hash = hashImage(data);
  if (summaryCache.has(hash)) {
    return summaryCache.get(hash)!;
  }
  if (inFlightSummaries.has(hash)) {
    return inFlightSummaries.get(hash)!;
  }

  const promise = (async () => {
    try {
      const model = ctx.modelRegistry?.find(SUMMARY_PROVIDER, SUMMARY_MODEL_ID);
      const provider = ctx.modelRegistry?.getProvider(SUMMARY_PROVIDER);
      if (!model || !provider) {
        return `[Automatic image summary unavailable: ${SUMMARY_PROVIDER}/${SUMMARY_MODEL_ID} is not registered]`;
      }

      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      if (!auth.ok) {
        return `[Automatic image summary unavailable: ${auth.error}]`;
      }

      const promptText =
        "Analyze this image carefully. Describe its main features, structure, layout, visible text, labels, numbers, data trends, plot axes, or UI state concisely so a non-vision model can understand it.";

      const response = await provider
        .streamSimple(
          model,
          {
            systemPrompt:
              "You are an expert visual analyzer providing concise, high-density factual descriptions of images, diagrams, charts, screenshots, and plots for non-vision coding agents.",
            messages: [
              {
                role: "user",
                content: [
                  { type: "text", text: promptText },
                  { type: "image", mimeType: mimeType || "image/png", data },
                ],
                timestamp: Date.now(),
              },
            ],
          },
          {
            apiKey: auth.apiKey,
            headers: auth.headers,
            env: auth.env,
            maxTokens: 4096,
            reasoning: "high",
            cacheRetention: "none",
            sessionId: uuidv7(),
          },
        )
        .result();

      const summaryText = response.content
        .filter((block: any): block is { type: "text"; text: string } => block.type === "text")
        .map((block: any) => block.text)
        .join("\n")
        .trim();

      if (!summaryText) {
        return "[Automatic image summary unavailable: empty model response]";
      }

      summaryCache.set(hash, summaryText);
      return summaryText;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return `[Automatic image summary failed: ${msg}]`;
    } finally {
      inFlightSummaries.delete(hash);
    }
  })();

  inFlightSummaries.set(hash, promise);
  return promise;
}

export default function imageFallback(pi: ExtensionAPI) {
  pi.on("context", async (event, ctx) => {
    const currentModel = ctx.model;
    if (!currentModel) return;

    // Vision models support image input natively. Pass through untouched.
    const supportsVision = Array.isArray(currentModel.input) && currentModel.input.includes("image");
    if (supportsVision) return;

    const messages: AgentMessage[] = event.messages;
    let modified = false;

    const transformedMessages: AgentMessage[] = await Promise.all(
      messages.map(async (msg) => {
        if (typeof msg.content === "string" || !Array.isArray(msg.content)) {
          return msg;
        }

        const hasImages = msg.content.some((block: any) => block.type === "image");
        if (!hasImages) return msg;

        modified = true;
        const newContent = await Promise.all(
          msg.content.map(async (block: any) => {
            if (block.type !== "image" || !block.data) {
              return block;
            }

            const summary = await summarizeImage(
              block.data,
              block.mimeType || "image/png",
              currentModel.id,
              ctx,
            );

            return {
              type: "text" as const,
              text: `[Image summary generated by ${SUMMARY_PROVIDER}/${SUMMARY_MODEL_ID} because ${currentModel.id} does not support image input]\n\n${summary}\n\n[/Image summary]`,
            };
          }),
        );

        return {
          ...msg,
          content: newContent,
        } as AgentMessage;
      }),
    );

    if (modified) {
      return { messages: transformedMessages };
    }
  });
}
